---
language: python
python: "2.7"

# Run jobs in a VM
sudo: required

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-virtualenv
      - realpath

install:
  - pip install tox
  - ssh-keygen -t rsa -N '' -f tools/test-ssh-key

script:
  - tools/container-deploy.sh
