---
language: python
python: "2.7"

# Use a VM.
sudo: required

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-virtualenv
      - realpath

env:
  # Increase ansible timeout to avoid hitting
  # https://github.com/ansible/ansible/issues/14426.
  - ANSIBLE_TIMEOUT=30

install:
  # Prepare the development configuration.
  - tools/travis-setup.sh
  # Deploy a CentOS controller container.
  - tools/container-deploy.sh
  # Install kayobe control host environment.
  - dev/install.sh

script:
  # Deploy the control plane.
  - dev/overcloud-deploy.sh
