---
language: python
python: "2.7"

# Use a container.
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-virtualenv
      - realpath

install:
  - pip install tox
  - ssh-keygen -t rsa -N '' -f tools/test-ssh-key

  # Install kayobe control host environment.
  - dev/install.sh

script:
  # Run the tox environment.
  - tox -e ${TOX_ENV}

jobs:
  include:
    - stage: Deployment test
      # Use a VM.
      sudo: required
      install:
        # Prepare the development configuration.
        - tools/travis-setup.sh
        # Deploy a CentOS controller container.
        - tools/container-deploy.sh
        # Install kayobe control host environment.
        - dev/install.sh
      script:
        # Deploy the control plane.
        - dev/overcloud-deploy.sh
