---
language: python
python: "2.7"

# Run jobs in containers.
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-virtualenv
      - realpath

# Create a build matrix for the different test jobs.
env:
  matrix:
    # Run python style checks.
    - TOX_ENV=pep8
    # Build documentation.
    - TOX_ENV=docs
    # Run python2.7 unit tests.
    - TOX_ENV=py27
    # Run ansible syntax checks.
    - TOX_ENV=ansible-syntax
    # Run ansible-lint.
    - TOX_ENV=ansible-lint

matrix:
  allow_failues:
    # Ansible-lint is currently advisory.
    - env: TOX_ENV=ansible-lint

install:
  - pip install tox

script:
  # Run the tox environment.
  - tox -e ${TOX_ENV}
