---
# List of custom configuration files.
# Each item is a dict containing the following items:
# src: Path to a configuration file template.
# dest: Path to file in which generated files will be created.
# enabled: Whether this file should be templated.
kolla_openstack_custom_config_files:
  # Ceph - ceph.conf.
  - src: "{{ kolla_extra_config_path }}/ceph.conf"
    dest: "{{ kolla_node_custom_config_path }}/ceph.conf"
    enabled: "{{ kolla_enable_ceph }}"
  # Cinder - cinder.conf.
  - src: "{{ kolla_extra_config_path }}/cinder.conf"
    dest: "{{ kolla_node_custom_config_path }}/cinder.conf"
    enabled: "{{ kolla_enable_cinder }}"
  # Designate - designate.conf.
  - src: "{{ kolla_extra_config_path }}/designate.conf"
    dest: "{{ kolla_node_custom_config_path }}/designate.conf"
    enabled: "{{ kolla_enable_designate }}"
  # Grafana - grafana.ini.
  - src: "{{ kolla_extra_config_path }}/grafana.ini"
    dest: "{{ kolla_node_custom_config_path }}/grafana.ini"
    enabled: "{{ kolla_enable_grafana }}"
  # Heat - heat.conf.
  - src: "{{ kolla_extra_config_path }}/heat.conf"
    dest: "{{ kolla_node_custom_config_path }}/heat.conf"
    enabled: "{{ kolla_enable_heat }}"
  # InfluxDB - influxdb.conf.
  - src: "{{ kolla_extra_config_path }}/influxdb.conf"
    dest: "{{ kolla_node_custom_config_path }}/influxdb.conf"
    enabled: "{{ kolla_enable_influxdb }}"
  # Kafka - kafka.server.properties.
  - src: "{{ kolla_extra_config_path }}/kafka.server.properties"
    dest: "{{ kolla_node_custom_config_path }}/kafka.server.properties"
    enabled: "{{ kolla_enable_kafka }}"
  # Keystone - keystone.conf.
  - src: "{{ kolla_extra_config_path }}/keystone.conf"
    dest: "{{ kolla_node_custom_config_path }}/keystone.conf"
    enabled: true
  # Magnum - magnum.conf.
  - src: "{{ kolla_extra_config_path }}/magnum.conf"
    dest: "{{ kolla_node_custom_config_path }}/magnum.conf"
    enabled: "{{ kolla_enable_magnum }}"
  # Manila - manila.conf.
  - src: "{{ kolla_extra_config_path }}/manila.conf"
    dest: "{{ kolla_node_custom_config_path }}/manila.conf"
    enabled: "{{ kolla_enable_manila }}"
  # Mariadb - galera.cnf.
  - src: "{{ kolla_extra_config_path }}/galera.cnf"
    dest: "{{ kolla_node_custom_config_path }}/galera.cnf"
    enabled: "{{ kolla_enable_mariadb }}"
  # Murano - murano.conf.
  - src: "{{ kolla_extra_config_path }}/murano.conf"
    dest: "{{ kolla_node_custom_config_path }}/murano.conf"
    enabled: "{{ kolla_enable_murano }}"
  # Neutron - neutron.conf.
  - src: "{{ kolla_extra_config_path }}/neutron.conf"
    dest: "{{ kolla_node_custom_config_path }}/neutron.conf"
    enabled: "{{ kolla_enable_neutron }}"
  # Nova - nova.conf.
  - src: "{{ kolla_extra_config_path }}/nova.conf"
    dest: "{{ kolla_node_custom_config_path }}/nova.conf"
    enabled: "{{ kolla_enable_nova }}"
  # Sahara - sahara.conf.
  - src: "{{ kolla_extra_config_path }}/sahara.conf"
    dest: "{{ kolla_node_custom_config_path }}/sahara.conf"
    enabled: "{{ kolla_enable_sahara }}"
  # Zookeeper - zookeeper.cfg.
  - src: "{{ kolla_extra_config_path }}/zookeeper.cfg"
    dest: "{{ kolla_node_custom_config_path }}/zookeeper.cfg"
    enabled: "{{ kolla_enable_zookeeper }}"

# List of custom configuration directories.
# Each item is a dict containing the following items:
# src: Path to a directory containing configuration file templates.
# dest: Path to directory in which generated files will be created.
# patterns: One or more file name patterns to match.
# enabled: Whether these files should be templated.
# ignore: Optional list of files to ignore. These files will not be copied to
#         the destination, and will not be removed from the destination, even
#         if disabled or unexpected.
kolla_openstack_custom_config_dirs:
  # Ceph - ceph/*.
  - src: "{{ kolla_extra_config_path }}/ceph"
    dest: "{{ kolla_node_custom_config_path }}/ceph"
    patterns: "*"
    enabled: "{{ kolla_enable_ceph }}"
  # Cinder - cinder/*.
  - src: "{{ kolla_extra_config_path }}/cinder"
    dest: "{{ kolla_node_custom_config_path }}/cinder"
    patterns: "*"
    enabled: "{{ kolla_enable_cinder }}"
  # Designate - designate/*.
  - src: "{{ kolla_extra_config_path }}/designate"
    dest: "{{ kolla_node_custom_config_path }}/designate"
    patterns: "*"
    enabled: "{{ kolla_enable_designate }}"
  # Fluentd filters.
  - src: "{{ kolla_extra_config_path }}//fluentd/filter"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/filter"
    patterns: "*.conf"
    enabled: true
  # Fluentd outputs.
  - src: "{{ kolla_extra_config_path }}/fluentd/output"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/output"
    patterns: "*.conf"
    enabled: true
  # Glance.
  - src: "{{ kolla_extra_config_path }}/glance"
    dest: "{{ kolla_node_custom_config_path }}/glance"
    patterns: "*"
    enabled: "{{ kolla_enable_glance }}"
  # Grafana - grafana/*.
  - src: "{{ kolla_extra_config_path }}/grafana"
    dest: "{{ kolla_node_custom_config_path }}/grafana"
    patterns: "*"
    enabled: "{{ kolla_enable_grafana }}"
  # Heat - heat/*.
  - src: "{{ kolla_extra_config_path }}/heat"
    dest: "{{ kolla_node_custom_config_path }}/heat"
    patterns: "*"
    enabled: "{{ kolla_enable_heat }}"
  # Horizon.
  - src: "{{ kolla_extra_config_path }}/horizon"
    dest: "{{ kolla_node_custom_config_path }}/horizon"
    patterns: "*"
    enabled: "{{ kolla_enable_horizon }}"
  # InfluxDB - influxdb/*.
  - src: "{{ kolla_extra_config_path }}/influxdb"
    dest: "{{ kolla_node_custom_config_path }}/influxdb"
    patterns: "*"
    enabled: "{{ kolla_enable_influxdb }}"
  # Ironic.
  - src: "{{ kolla_extra_config_path }}/ironic"
    dest: "{{ kolla_node_custom_config_path }}/ironic"
    patterns: "*"
    enabled: "{{ kolla_enable_ironic }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ironic-agent.initramfs
      - ironic-agent.kernel
      - ironic-dnsmasq.conf
      - pxelinux.default
      - inspector.ipxe
  # Kafka - kafka/*.
  - src: "{{ kolla_extra_config_path }}/kafka"
    dest: "{{ kolla_node_custom_config_path }}/kafka"
    patterns: "*"
    enabled: "{{ kolla_enable_kafka }}"
  # Keystone - keystone/*.
  - src: "{{ kolla_extra_config_path }}/keystone"
    dest: "{{ kolla_node_custom_config_path }}/keystone"
    patterns: "*"
    enabled: true
  # Magnum - magnum/*.
  - src: "{{ kolla_extra_config_path }}/magnum"
    dest: "{{ kolla_node_custom_config_path }}/magnum"
    patterns: "*"
    enabled: "{{ kolla_enable_magnum }}"
  # Manila - manila/*.
  - src: "{{ kolla_extra_config_path }}/manila"
    dest: "{{ kolla_node_custom_config_path }}/manila"
    patterns: "*"
    enabled: "{{ kolla_enable_manila }}"
  # MariaDB - mariadb/*.
  - src: "{{ kolla_extra_config_path }}/mariadb"
    dest: "{{ kolla_node_custom_config_path }}/mariadb"
    patterns: "*"
    enabled: "{{ kolla_enable_mariadb }}"
  # Murano - murano/*.
  - src: "{{ kolla_extra_config_path }}/murano"
    dest: "{{ kolla_node_custom_config_path }}/murano"
    patterns: "*"
    enabled: "{{ kolla_enable_murano }}"
  # Neutron - neutron/*.
  - src: "{{ kolla_extra_config_path }}/neutron"
    dest: "{{ kolla_node_custom_config_path }}/neutron"
    patterns: "*"
    enabled: "{{ kolla_enable_neutron }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ml2_conf.ini
  # Nova - nova/*.
  - src: "{{ kolla_extra_config_path }}/nova"
    dest: "{{ kolla_node_custom_config_path }}/nova"
    patterns: "*"
    enabled: "{{ kolla_enable_nova }}"
  # Sahara - sahara/*.
  - src: "{{ kolla_extra_config_path }}/sahara"
    dest: "{{ kolla_node_custom_config_path }}/sahara"
    patterns: "*"
    enabled: "{{ kolla_enable_sahara }}"
  # Swift - swift/*.
  - src: "{{ kolla_extra_config_path }}/swift"
    dest: "{{ kolla_node_custom_config_path }}/swift"
    patterns: "*"
    enabled: "{{ kolla_enable_swift }}"
  # Zookeeper - zookeeper/*.
  - src: "{{ kolla_extra_config_path }}/zookeeper"
    dest: "{{ kolla_node_custom_config_path }}/zookeeper"
    patterns: "*"
    enabled: "{{ kolla_enable_zookeeper }}"
