---
# Variables:
# - dump_path: Path to directory to store variable dumps (optional)
# - dump_facts: Whether to include gathered facts in the dump (optional)
# - dump_hosts: Group/host specifier for hosts to dump (optional)
# - dump_var_name: Name of the option to dump (optional)
# - dump_json_query: JMESPath query to perform on data (optional)
# - dump_expression: Jinja2 expression to resolve (optional)

- name: Dump configuration from one or more hosts
  hosts: "{{ dump_hosts }}"
  gather_facts: "{{ dump_facts }}"
  tags:
    - dump-config
  vars:
    dump_path: /tmp/kayobe-dump-config
    dump_facts: no
    dump_hosts: all
    dump_json_query:
    dump_expression:
  tasks:
    - name: Create configuration dump directory
      local_action:
        module: file
        path: "{{ dump_path }}"
        state: directory

    - name:
      set_fact:
        result: "{{ dump_expression }}"
      when: dump_expression is not none

    - block:
        - name:
          set_fact:
            result: "{{ hostvars[inventory_hostname] }}"
          when: dump_var_name is not defined

        - name:
          set_fact:
            result: "{{ hostvars[inventory_hostname][dump_var_name] }}"
          when: dump_var_name is defined

        - name:
          set_fact:
            result: "{{ {dump_var_name|default('hostvars'): result} | json_query(dump_json_query) }}"
          when: dump_json_query is not none
      when: dump_expression is none

    - name: Write host config to file
      local_action:
        module: copy
        content: "{{ result | to_nice_yaml }}"
        dest: "{{ dump_path }}/{{ inventory_hostname }}.yml"
